services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: food_manager_api_v1
    working_dir: /service
    volumes:
      - .:/service
    env_file:
      - .env
    environment:
      - APP_PORT=$APP_PORT
    ports:
      - "3000:${APP_PORT}"
    command: pnpm run start:dev
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      # - MONGO_INITDB_DATABASE=local
      - DB_PORT=$DB_PORT
    ports:
      - "27017:${DB_PORT}"
